version: '3.7'
services:
    php-build:
        build:
            context: .
            dockerfile: php-build.dockerfile
        image: creativecow/magento-php-build-test
        restart: on-failure
        tty: true
        volumes:
            - composer:/home/cli/.composer
            - magento-media:/var/www/magento/pub/media
            - magento-var:/var/www/magento/va
volumes:
    composer: