version: '3.7'
services:
    varnish:
        image: creativecow/magento-varnish
        restart: unless-stopped
        ports:
            - 80:80/tcp
        links:
            - nginx
    nginx:
        build:
            context: .
            dockerfile: nginx.dockerfile
        image: creativecow/magento-nginx-test
        restart: unless-stopped
        volumes:
            - magento-media:/var/www/magento/pub/media
        links:
            - php-fpm
    php-fpm:
        build:
            context: .
            dockerfile: php-fpm.dockerfile
        image: creativecow/magento-php-fpm-test
        restart: unless-stopped
        volumes:
            - magento-media:/var/www/magento/pub/media
            - magento-var:/var/www/magento/var
        depends_on:
            - php-build
        links:
            - elasticsearch
            - mysql
            - redis
    php-cron:
        build:
            context: .
            dockerfile: php-cron.dockerfile
        image: creativecow/magento-php-cron-test
        restart: unless-stopped
        volumes:
            - magento-media:/var/www/magento/pub/media
            - magento-var:/var/www/magento/var
        depends_on:
            - php-build
        links:
            - elasticsearch
            - mysql
            - redis
    mysql:
        image: creativecow/magento-mysql
        restart: unless-stopped
        volumes:
            - mysql:/var/lib/mysql
    redis:
        image: creativecow/magento-redis
        restart: unless-stopped
        volumes:
            - redis:/data
        privileged: true
        sysctls:
            - net.core.somaxconn=1024
    elasticsearch:
        image: creativecow/magento-elasticsearch
        restart: unless-stopped
        volumes:
            - elasticsearch:/usr/share/elasticsearch/data
        ulimits:
            memlock:
                soft: -1
                hard: -1
volumes:
    elasticsearch:
    magento-media:
    magento-var:
    mysql:
    redis: