version: '3.7'
services:
    php-cli:
        volumes:
            - ./src:/var/www/magento
    nginx:
        volumes:
            - ./src:/var/www/magento
    php-fpm:
        volumes:
            - ./src:/var/www/magento
    php-cron:
        volumes:
            - ./src:/var/www/magento